### ISSUE TITLE
Error when uploading an image

### ISSUE THREAD

**Issue by sdushantha** [ujjwal96/pywal-web#6]
When i try to upload an image it gives me this error message.
```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "server.py", line 26, in post
    colors = pywal.colors.get(path, light=light, backend=backend)
  File "/app/.heroku/python/lib/python3.6/site-packages/pywal/colors.py", line 139, in get
    colors = colors_to_dict(getattr(backend, "get")(img, light), img)
  File "/app/.heroku/python/lib/python3.6/site-packages/pywal/backends/wal.py", line 86, in get
    colors = gen_colors(img)
  File "/app/.heroku/python/lib/python3.6/site-packages/pywal/backends/wal.py", line 41, in gen_colors
    raw_colors = imagemagick(16 + i, img, magick_command)
  File "/app/.heroku/python/lib/python3.6/site-packages/pywal/backends/wal.py", line 19, in imagemagick
    return subprocess.check_output([*magick_command, img, *flags]).splitlines()
  File "/app/.heroku/python/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/app/.heroku/python/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['convert', '/tmp/tmpu3xs1ozu[0]', '-resize', '25%', '-colors', '16', '-unique-colors', 'txt:-']' returned non-zero exit status 1.
```

**Comment by r00tdaemon** [comment]
What browser/device are you using?
Will it be possible for you too share the image?

**Comment by sdushantha** [comment]
I am using Firefox on Ubuntu 18 on a MacBook Air by dual boot.

I think the error happens when I upload a PNG file.

Here is the image I used.
![lgbt](https://user-images.githubusercontent.com/27065646/42285085-be9e0526-7fae-11e8-82e9-acbffa38ce1e.png)
