### ISSUE TITLE
Can't select an image to upload

### ISSUE THREAD

**Issue by Kyle-Thompson** [ujjwal96/pywal-web#7]
When I click the upload button I'm given this

    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "server.py", line 19, in post
        file1 = self.request.files.get("file1")[0]
    TypeError: 'NoneType' object is not subscriptable

I'm on Arch using Chrome.

**Comment by r00tdaemon** [comment]
Thanks for reporting. Can you share the image?
